name = "medbag_advanced";
creativeTab = "Medicine";
maxStack = 1;
maxDamage = 8;
repairable = false;
addToCreative[0] = true;
onUseOnPlayer[0] = "mod.loadScript('bandage_bag_use.js');";
textureFile[0] = "meds_bag_red";
information[0] = "Sneak-right click to patch up a partner.|§9Heals target for 2.5 hearts.§r|§eCraft with up to 8 Bandages to refill.|§eCraft alone to retrieve a Bandage.§r"