name = "medbag_advanced";
creativeTab = "Medicine";
maxStack = 1;
maxDamage = 8;
addToCreative[0] = true;
onUseOnPlayer[0] = "mod.loadScript('bandage_bag_use.js');";
textureFile[0] = "meds_bag_red";
information[8] = "Needs to be sterilized."
information[7] = "Sneak-click to patch|up a partner."
information[6] = "Sneak-click to patch|up a partner."
information[5] = "Sneak-click to patch|up a partner."
information[4] = "Sneak-click to patch|up a partner."
information[3] = "Sneak-click to patch|up a partner."
information[2] = "Sneak-click to patch|up a partner."
information[1] = "Sneak-click to patch|up a partner."
information[0] = "Sneak-click to patch|up a partner."