name = "potion";
creativeTab = "Medicine";
maxStack = 1;

addToCreative[4] = true;
textureFile[4] = "vial_red";
alwaysEdible[4] = true;
usingAction[4] = "drink";
potion[4] = "nightVision";
potionAmplifier[4] = 0;
potionDuration[4] = 45;
potionProbability[4] = 1;
hunger[4] = 0
information[4] = "Duration: 45 seconds"

addToCreative[5] = true;
textureFile[5] = "vial_orange";
alwaysEdible[5] = true;
usingAction[5] = "drink";
potion[5] = "jump";
potionAmplifier[5] = 0;
potionDuration[5] = 45;
potionProbability[5] = 1;
hunger[5] = 0
information[4] = "Duration: 45 seconds"

addToCreative[6] = true;
textureFile[6] = "vial_pink";
alwaysEdible[6] = true;
usingAction[6] = "drink";
potion[6] = "invisibility";
potionAmplifier[6] = 0;
potionDuration[6] = 45;
potionProbability[6] = 1;
hunger[6] = 0
information[4] = "Duration: 45 seconds"

addToCreative[7] = true;
textureFile[7] = "vial_purple";
alwaysEdible[7] = true;
usingAction[7] = "drink";
potion[7] = "poison";
potionAmplifier[7] = 255;
potionDuration[7] = 0;
potionProbability[7] = 1;
hunger[7] = 0
information[4] = "Cures poison."

addToCreative[8] = true;
textureFile[8] = "vial_magenta";
alwaysEdible[8] = true;
usingAction[8] = "drink";
potion[8] = "digSpeed";
potionAmplifier[8] = 0;
potionDuration[8] = 45;
potionProbability[8] = 1;
hunger[8] = 0
information[4] = "Duration: 45 seconds"

addToCreative[9] = true;
textureFile[9] = "vial_yellow";
alwaysEdible[9] = true;
usingAction[9] = "drink";
potion[9] = "absorption";
potionAmplifier[9] = 0;
potionDuration[9] = 45;
potionProbability[9] = 1;
hunger[9] = 0
information[4] = "Duration: 45 seconds"

addToCreative[10] = true;
textureFile[10] = "vial_white";
alwaysEdible[10] = true;
usingAction[10] = "drink";
potion[10] = "damageBoost";
potionAmplifier[10] = 0;
potionDuration[10] = 45;
potionProbability[10] = 1;
hunger[10] = 0
information[4] = "Duration: 45 seconds"

addToCreative[11] = true;
textureFile[11] = "vial_ltblue";
alwaysEdible[11] = true;
usingAction[11] = "drink";
potion[11] = "moveSpeed";
potionAmplifier[11] = 0;
potionDuration[11] = 45;
potionProbability[11] = 1;
hunger[11] = 0
information[4] = "Duration: 45 seconds"

addToCreative[12] = true;
textureFile[12] = "vial_brown";
alwaysEdible[12] = true;
usingAction[12] = "drink";
potion[12] = "fireResistance";
potionAmplifier[12] = 0;
potionDuration[12] = 45;
potionProbability[12] = 1;
hunger[12] = 0
information[4] = "Duration: 45 seconds"

addToCreative[13] = true;
textureFile[13] = "vial_ltgrey";
alwaysEdible[13] = true;
usingAction[13] = "drink";
potion[13] = "resistance";
potionAmplifier[13] = 0;
potionDuration[13] = 45;
potionProbability[13] = 1;
hunger[13] = 0
information[4] = "Duration: 45 seconds"

addToCreative[14] = true;
textureFile[14] = "vial_blue";
alwaysEdible[14] = true;
usingAction[14] = "drink";
potion[14] = "waterBreathing";
potionAmplifier[14] = 0;
potionDuration[14] = 45;
potionProbability[14] = 1;
hunger[14] = 0
information[4] = "Duration: 45 seconds"