name = "potion";
creativeTab = "Medicine";
maxStack = 1;

addToCreative[0] = true;
textureFile[0] = "potion_red";
alwaysEdible[0] = true;
usingAction[0] = "drink";
potion[0] = "nightVision";
potionDuration[0] = 120;
potionAmplifier[0] = 0;
potionProbability[0] = 1;
hunger[0] = 0
information[0] = "Duration: 2m0s";

addToCreative[1] = true;
textureFile[1] = "potion_red";
alwaysEdible[1] = true;
usingAction[1] = "drink";
potion[1] = "nightVision";
potionDuration[1] = 300;
potionAmplifier[1] = 0;
potionProbability[1] = 1;
hunger[1] = 0
hasEffect[1] = true;
information[1] = "Duration: 5m0s";

addToCreative[2] = true;
textureFile[2] = "potion_orange";
alwaysEdible[2] = true;
usingAction[2] = "drink";
potion[2] = "jump";
potionDuration[2] = 120;
potionAmplifier[2] = 1;
potionProbability[2] = 1;
hunger[2] = 0
information[2] = "Duration: 2m0s";

addToCreative[3] = true;
textureFile[3] = "potion_orange";
alwaysEdible[3] = true;
usingAction[3] = "drink";
potion[3] = "jump";
potionDuration[3] = 300;
potionAmplifier[3] = 1;
potionProbability[3] = 1;
hunger[3] = 0
hasEffect[3] = true;
information[3] = "Duration: 5m0s";

addToCreative[4] = true;
textureFile[4] = "potion_orange";
alwaysEdible[4] = true;
usingAction[4] = "drink";
potion[4] = "jump";
potionDuration[4] = 90;
potionAmplifier[4] = 2;
potionProbability[4] = 1;
hunger[4] = 0
hasEffect[4] = true;
information[4] = "Duration: 1m30s";

addToCreative[5] = true;
textureFile[5] = "potion_pink";
alwaysEdible[5] = true;
usingAction[5] = "drink";
potion[5] = "invisibility";
potionDuration[5] = 120;
potionAmplifier[5] = 0;
potionProbability[5] = 1;
hunger[5] = 0
information[5] = "Duration: 2m0s";

addToCreative[6] = true;
textureFile[6] = "potion_pink";
alwaysEdible[6] = true;
usingAction[6] = "drink";
potion[6] = "invisibility";
potionDuration[6] = 300;
potionAmplifier[6] = 0;
potionProbability[6] = 1;
hunger[6] = 0
hasEffect[6] = true;
information[6] = "Duration: 5m0s";

addToCreative[7] = true;
textureFile[7] = "potion_magenta";
alwaysEdible[7] = true;
usingAction[7] = "drink";
potion[7] = "digSpeed";
potionDuration[7] = 120;
potionAmplifier[7] = 0;
potionProbability[7] = 1;
hunger[7] = 0
information[7] = "Duration: 2m0s";

addToCreative[8] = true;
textureFile[8] = "potion_magenta";
alwaysEdible[8] = true;
usingAction[8] = "drink";
potion[8] = "digSpeed";
potionDuration[8] = 300;
potionAmplifier[8] = 0;
potionProbability[8] = 1;
hunger[8] = 0
hasEffect[8] = true;
information[8] = "Duration: 5m0s";

addToCreative[9] = true;
textureFile[9] = "potion_magenta";
alwaysEdible[9] = true;
usingAction[9] = "drink";
potion[9] = "digSpeed";
potionDuration[9] = 90;
potionAmplifier[9] = 1;
potionProbability[9] = 1;
hunger[9] = 0
hasEffect[9] = true;
information[9] = "Duration: 1m30s";

addToCreative[10] = true;
textureFile[10] = "potion_yellow";
alwaysEdible[10] = true;
usingAction[10] = "drink";
potion[10] = "absorption";
potionDuration[10] = 120;
potionAmplifier[10] = 0;
potionProbability[10] = 1;
hunger[10] = 0
information[10] = "Duration: 2m0s";

addToCreative[11] = true;
textureFile[11] = "potion_yellow";
alwaysEdible[11] = true;
usingAction[11] = "drink";
potion[11] = "absorption";
potionDuration[11] = 300;
potionAmplifier[11] = 0;
potionProbability[11] = 1;
hunger[11] = 0
hasEffect[11] = true;
information[11] = "Duration: 5m0s";

addToCreative[12] = true;
textureFile[12] = "potion_yellow";
alwaysEdible[12] = true;
usingAction[12] = "drink";
potion[12] = "absorption";
potionDuration[12] = 90;
potionAmplifier[12] = 1;
potionProbability[12] = 1;
hunger[12] = 0
hasEffect[12] = true;
information[12] = "Duration: 1m30s";

addToCreative[13] = true;
textureFile[13] = "potion_white";
alwaysEdible[13] = true;
usingAction[13] = "drink";
potion[13] = "damageBoost";
potionDuration[13] = 120;
potionAmplifier[13] = 0;
potionProbability[13] = 1;
hunger[13] = 0
information[13] = "Duration: 2m0s";

addToCreative[14] = true;
textureFile[14] = "potion_white";
alwaysEdible[14] = true;
usingAction[14] = "drink";
potion[14] = "damageBoost";
potionDuration[14] = 300;
potionAmplifier[14] = 0;
potionProbability[14] = 1;
hunger[14] = 0
hasEffect[14] = true;
information[14] = "Duration: 5m0s";

addToCreative[15] = true;
textureFile[15] = "potion_white";
alwaysEdible[15] = true;
usingAction[15] = "drink";
potion[15] = "damageBoost";
potionDuration[15] = 90;
potionAmplifier[15] = 1;
potionProbability[15] = 1;
hunger[15] = 0
hasEffect[15] = true;
information[15] = "Duration: 1m30s";

addToCreative[16] = true;
textureFile[16] = "potion_ltblue";
alwaysEdible[16] = true;
usingAction[16] = "drink";
potion[16] = "moveSpeed";
potionDuration[16] = 120;
potionAmplifier[16] = 0;
potionProbability[16] = 1;
hunger[16] = 0
information[16] = "Duration: 2m0s";

addToCreative[17] = true;
textureFile[17] = "potion_ltblue";
alwaysEdible[17] = true;
usingAction[17] = "drink";
potion[17] = "moveSpeed";
potionDuration[17] = 300;
potionAmplifier[17] = 0;
potionProbability[17] = 1;
hunger[17] = 0
hasEffect[17] = true;
information[17] = "Duration: 5m0s";

addToCreative[18] = true;
textureFile[18] = "potion_ltblue";
alwaysEdible[18] = true;
usingAction[18] = "drink";
potion[18] = "moveSpeed";
potionDuration[18] = 90;
potionAmplifier[18] = 1;
potionProbability[18] = 1;
hunger[18] = 0
hasEffect[18] = true;
information[18] = "Duration: 1m30s";

addToCreative[19] = true;
textureFile[19] = "potion_brown";
alwaysEdible[19] = true;
usingAction[19] = "drink";
potion[19] = "fireResistance";
potionDuration[19] = 120;
potionAmplifier[19] = 0;
potionProbability[19] = 1;
hunger[19] = 0
information[19] = "Duration: 2m0s";

addToCreative[20] = true;
textureFile[20] = "potion_brown";
alwaysEdible[20] = true;
usingAction[20] = "drink";
potion[20] = "fireResistance";
potionDuration[20] = 300;
potionAmplifier[20] = 0;
potionProbability[20] = 1;
hunger[20] = 0
hasEffect[20] = true;
information[20] = "Duration: 5m0s";

addToCreative[21] = true;
textureFile[21] = "potion_ltgrey";
alwaysEdible[21] = true;
usingAction[21] = "drink";
potion[21] = "resistance";
potionDuration[21] = 120;
potionAmplifier[21] = 0;
potionProbability[21] = 1;
hunger[21] = 0
information[21] = "Duration: 2m0s";

addToCreative[22] = true;
textureFile[22] = "potion_ltgrey";
alwaysEdible[22] = true;
usingAction[22] = "drink";
potion[22] = "resistance";
potionDuration[22] = 300;
potionAmplifier[22] = 0;
potionProbability[22] = 1;
hunger[22] = 0
hasEffect[22] = true;
information[22] = "Duration: 5m0s";

addToCreative[23] = true;
textureFile[23] = "potion_ltgrey";
alwaysEdible[23] = true;
usingAction[23] = "drink";
potion[23] = "resistance";
potionDuration[23] = 90;
potionAmplifier[23] = 1;
potionProbability[23] = 1;
hunger[23] = 0
hasEffect[23] = true;
information[23] = "Duration: 1m30s";

addToCreative[24] = true;
textureFile[24] = "potion_blue";
alwaysEdible[24] = true;
usingAction[24] = "drink";
potion[24] = "waterBreathing";
potionDuration[24] = 120;
potionAmplifier[24] = 0;
potionProbability[24] = 1;
hunger[24] = 0
information[24] = "Duration: 2m0s";

addToCreative[25] = true;
textureFile[25] = "potion_blue";
alwaysEdible[25] = true;
usingAction[25] = "drink";
potion[25] = "waterBreathing";
potionDuration[25] = 300;
potionAmplifier[25] = 0;
potionProbability[25] = 1;
hunger[25] = 0
hasEffect[25] = true;
information[25] = "Duration: 5m0s";

addToCreative[31] = true;
textureFile[31] = 'potion_purple';
alwaysEdible[31] = true;
usingAction[31] = 'drink';
onEaten[31] = 'player.addPotionEffect("poison", 0, 255); player.addPotionEffect("wither", 0, 255);
hunger[31] = 0;
information[31] = 'Cures poison and wither.';
